//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeetingScheduler.Repository.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeetingScheduler.Repository.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO Meeting(Title, [Description], [Time], CreatedBy)
        ///  VALUES(@Title, @Description, @Time, @CreatedBy).
        /// </summary>
        internal static string CREATE_MEETING {
            get {
                return ResourceManager.GetString("CREATE_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE FROM Meeting WHERE MeetingId = @MeetingId.
        /// </summary>
        internal static string DELETE_MEETING {
            get {
                return ResourceManager.GetString("DELETE_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [MeetingId]
        ///      ,[Title]
        ///      ,[Description]
        ///      ,[Time]
        ///      ,[CreatedBy] 
        ///  FROM [MeetingScheduler].[dbo].[Meeting].
        /// </summary>
        internal static string SELECT_ALL_MEETING {
            get {
                return ResourceManager.GetString("SELECT_ALL_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT [MeetingId]
        ///      ,[Title]
        ///      ,[Description]
        ///      ,[Time]
        ///      ,[CreatedBy] 
        ///  FROM [MeetingScheduler].[dbo].[Meeting]
        /// WHERE [MeetingId] = @MeetingId.
        /// </summary>
        internal static string SELECT_MEETING {
            get {
                return ResourceManager.GetString("SELECT_MEETING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT UserId AS &apos;UserId&apos;, Username AS &apos;Username&apos;, Password AS &apos;Password&apos;
        ///FROM [User] WHERE Username = @Username.
        /// </summary>
        internal static string SIGNIN {
            get {
                return ResourceManager.GetString("SIGNIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO [User] (Username, [Password]) VALUES (@Username, @Password).
        /// </summary>
        internal static string SIGNUP {
            get {
                return ResourceManager.GetString("SIGNUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPDATE Meeting
        ///  SET Title = @Title, [Description] = @Description, [Time] = @Time
        ///  WHERE MeetingId = @MeetingId.
        /// </summary>
        internal static string UPDATE_MEETING {
            get {
                return ResourceManager.GetString("UPDATE_MEETING", resourceCulture);
            }
        }
    }
}
